#!/usr/bin/env python
# Copyright 2012-2020 CERN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Vincent Garonne, <vincent.garonne@cern.ch>, 2015
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Fernando Garzon, <oscar.fernando.garzon.miguez@cern.ch>, 2021

'''
Probe to check the free space at each rse.
'''

import sys
import traceback

from prometheus_client import CollectorRegistry, Gauge
from rucio.api.rse import list_rses, get_rse_usage
from rucio.common.config import config_get

from utils import common

PrometheusPusher = common.PrometheusPusher

##PROM_SERVERS = config_get('monitor', 'prometheus_servers', raise_exception=False, default='')
#if PROM_SERVERS != '':
#    PROM_SERVERS = PROM_SERVERS.split(',')

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3


if __name__ == '__main__':
    registry = CollectorRegistry()
    labelnames = ['rse']
    try:
        with PrometheusPusher(registry, job_name='check_free_space') as prometheus_config:
            extra_prom_labels = prometheus_config['labels']
            prefix: str = prometheus_config['prefix']
            labelnames.extend(extra_prom_labels.keys())
            free_space_gauge = Gauge(prefix + 'report_free_space',
                                 'Free space at each site', labelnames=labelnames, registry=registry)
        for rse in list_rses():
            limits = get_rse_usage(rse['rse'], issuer='transfer_ops')
            rucio_used = None
            static_used = None
            for usage in limits:
                if usage['source'] == 'rucio':
                    rucio_used = usage['used']
                if usage['source'] == 'static':
                    static_used = usage['used']
            if (rucio_used is None) or (static_used is None):
                free_space = None
            else:
                free_space = int(static_used) - int(rucio_used)
                prom_labels = {'rse': rse['rse']}
                prom_labels.update(extra_prom_labels)
                print(rse['rse'], free_space)
                free_space_gauge.labels(**prom_labels).set(free_space)

    except:
        print (traceback.format_exc())
        sys.exit(UNKNOWN)
        
