#!/usr/bin/env python3
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Eric Vaandering, <ewv@fnal.gov>, 2021

"""
Probe to check the free space at each rse.
"""

import sys
import traceback

from rucio.core.rse import list_rses, get_rse_usage

from utils import common

probe_metrics = common.probe_metrics

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == "__main__":
    try:
        for rse in list_rses():
            limits = get_rse_usage(rse['id'])
            for usage in limits:
                if usage['source'] == 'rucio':
                    free_space = int(usage['total']) - int(usage['used'])
                    probe_metrics.gauge('judge.free_space.{rse}').labels(rse=rse['rse']).set(free_space)

    except:
        print(traceback.format_exc())
        sys.exit(UNKNOWN)
    sys.exit(OK)
