#!/usr/bin/env python3
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Eric Vaandering, <ewv@fnal.gov>, 2021

"""
Probe to check the number of not OK rules per rse.
"""

import sys
import traceback

from rucio.core import monitor
from rucio.db.sqla.session import BASE, get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if BASE.metadata.schema:
    schema = BASE.metadata.schema + '.'
else:
    schema = ''

if __name__ == "__main__":
    try:
        session = get_session()
        sql = """select /*+ index_ffs(REQUESTS REQUESTS_TYP_STA_CRE_IDX) */ {schema}rses.rse rse, COUNT (DISTINCT rule_id) \
                 from {schema}requests \
                 join {schema}rses on requests.dest_rse_id = rses.id \
                 join {schema}rules on requests.rule_id = rules.id \
                 where request_type='T' and rules.state!='O' \
                 group by {schema}rses.rse""".format(schema=schema)
        result = session.execute(sql).fetchall()
        for rse, count in result:
            monitor.record_gauge('not_OK_rules.%s' % rse, value=count)
        sql = """select /*+ index_ffs(REQUESTS REQUESTS_TYP_STA_CRE_IDX) */ {schema}rses.rse rse, COUNT (DISTINCT rule_id) \
                 from {schema}requests \
                 join {schema}rses on requests.dest_rse_id = rses.id \
                 join {schema}rules on requests.rule_id = rules.id \
                 where request_type='T' and rules.state='R' \
                 group by {schema}rses.rse""".format(schema=schema)
        result = session.execute(sql).fetchall()
        for rse, count in result:
            monitor.record_gauge('replicating_rules.%s' % rse, value=count)
    except:
        print(traceback.format_exc())
        sys.exit(UNKNOWN)
    sys.exit(OK)
