#!/usr/bin/env python
# Copyright 2012-2020 CERN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Fernando Garzon, <oscar.fernando.garzon.miguez@cern.ch>, 2020
# - Eric Vaandering, <ewv@fnal.gov>, 2021

'''
Probe to check total used space per RSE.
'''

import sys
import traceback
#from rucio.core.monitor import MultiGauge
from rucio.core.rse import list_rses, get_rse_usage, list_rse_attributes
from rucio.db.sqla import models
from rucio.db.sqla.session import get_session
from rucio.common.config import config_get


from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

PROM_SERVERS = config_get('monitor', 'prometheus_servers', raise_exception=False, default='')
if PROM_SERVERS != '':
    PROM_SERVERS = PROM_SERVERS.split(',')


# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == '__main__':
    registry = CollectorRegistry()
#    prom_metric = 'rucio_judge_used_space'
#    statsd_metric = 'judge.used_space_rucio.{rse}.{country}.{rse_type}.{source}'
#    space_gauge = MultiGauge(prom=prom_metric, statsd=statsd_metric, documentation='Space used at an RSE from various sources', labelnames=('rse','country','rse_type','source'))

    used_space_gauge = Gauge('rucio_judge_used_space','Space used at an RSE from various sources', labelnames=('rse','country','rse_type','source'), registry=registry)


    try:
        session = get_session()
        for rse in list_rses():
            sources = get_rse_usage(rse['id'])
            attributes = list_rse_attributes(rse['id'])
            country = attributes.get('country', 'UNKNOWN')
            rse_type = session.query(models.RSE.rse_type).filter(models.RSE.id == rse['id']).scalar()
            rse_type = str(rse_type).split('.', 1)[1]
            for usage in sources:
                source = usage['source']
                used_space_gauge.labels(rse=rse['rse'], country=country, rse_type=rse_type, source=source).set(usage['used'])
                #user_space_gauge.labels(**{'rse': rse['rse']}).set(free_space)

#(prom='rucio_daemons_hermes_reconnect', statsd='daemons.hermes.reconnect.{host}',
#3ib/rucio/daemons/hermes/hermes.py-                                 documentation='Counts Hermes reconnects to different ActiveMQ brokers', labelnames=('host',))
#                (prom='rucio_daemons_hermes_reconnect', statsd='daemons.hermes.reconnect.{host}',
#lib/rucio/daemons/hermes/hermes.py-                                 documentation='Counts Hermes reconnects to different ActiveMQ brokers', labelnames=('host',))



#                monitor.record_gauge(stat='judge.used_space_rucio.%s.%s.%s.%s' % (rse['rse'], country, rse_type, source), value=usage['used'])
                print(rse['rse'], country, rse_type, source, usage['used'])
        if len(PROM_SERVERS):
            for server in PROM_SERVERS:
                try:
                    push_to_gateway(server.strip(), job='check_report_used_space', registry=registry)
                except:
                    continue

    except:
        print (traceback.format_exc())
        sys.exit(UNKNOWN)