#!/usr/bin/env python
# Copyright 2012-2020 CERN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Fernando Garzon, <oscar.fernando.garzon.miguez@cern.ch>, 2020

'''
Probe to check used space.
'''

import sys
import traceback
from rucio.core import monitor
from rucio.core.rse import list_rses, get_rse_usage, list_rse_attributes
from rucio.db.sqla import models
from rucio.db.sqla.session import get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == '__main__':
    try:
        session = get_session()
        for rse in list_rses():
            sources = get_rse_usage(rse['id'])
            attributes = list_rse_attributes(rse['id'])
            country = attributes.get('country', 'UNKNOWN')
            rse_type = session.query(models.RSE.rse_type).filter(models.RSE.id == rse['id']).scalar()
            for usage in sources:
                source = usage['source']
                monitor.record_gauge(stat='judge.used_space_rucio.%s.%s.%s.%s' % (rse['rse'], country, rse_type, source), value=usage['used'])
                print(rse['rse'], country, rse_type, source, usage['used'])
    except:
        print (traceback.format_exc())
        sys.exit(UNKNOWN)
