#!/usr/bin/env python3
# Copyright 2012-2020 CERN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Eric Vaandering, <ewv@fnal.gov>, 2021


"""
Probe to check rules.
"""

import datetime
import sys
import traceback
import json

from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

from rucio.core import monitor
from rucio.db.sqla import models
from rucio.db.sqla.constants import (RuleState)
from rucio.db.sqla.session import get_session
from rucio.db.sqla.util import get_count
from rucio.common.config import config_get

from sqlalchemy import func

PROM_SERVERS = config_get('monitor', 'prometheus_servers', raise_exception=False, default='')
if PROM_SERVERS != '':
    PROM_SERVERS = PROM_SERVERS.split(',')
else:
    PROM_SERVERS = None

prom_labels_config = config_get('monitor', 'prometheus_labels', raise_exception=False, default='{}')
extra_prom_labels = json.loads(prom_labels_config)

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == '__main__':
    registry = CollectorRegistry()

    labelnames = ['state']
    not_ok_labels = ['Not_ok_rules']
    stuck_cnt_labels = ['Stuck_cnt']
    replicating_cnt_labels = ['Replicating_cnt']


    labelnames.extend(extra_prom_labels.keys())
    not_ok_labels.extend(extra_prom_labels.keys())
    stuck_cnt_labels.extend(extra_prom_labels.keys())
    replicating_cnt_labels.extend(extra_prom_labels.keys())


    rules_count_gauge = Gauge('rucio_judge_rules_state_count', 'Number of rules in a given state',
                              labelnames=labelnames, registry=registry)
    not_ok_rules_gauge = Gauge('rucio_not_ok_rules', 'Number of not OK rules',
                               labelnames=not_ok_labels, registry=registry)
    stuck_cnt_gauge = Gauge('rucio_stuck_cnt', 'Number of stuck files',
                            labelnames=stuck_cnt_labels, registry=registry)
    replicating_cnt_gauge = Gauge('rucio_replicating_cnt', 'Number of replicating files',
                                  labelnames=replicating_cnt_labels, registry=registry)


    try:
        session = get_session()

        # check rules
        state_map = {'REPLICATING': 'rules_replicating',
                     'OK': 'rules_ok',
                     'INJECT': 'rules_injecting',
                     'STUCK': 'rules_stuck',
                     'SUSPENDED': 'rules_suspend',
                     'WAITING_APPROVAL': 'rules_waiting_approval', }

        # I think both dictionaries in this part of the script are less confusing
        ages = {
            'created_24hours_ago': datetime.timedelta(days=1),
            'created_1week_ago': datetime.timedelta(days=7),
            'created_3weeks_ago': datetime.timedelta(days=21),
        }

        result = (session.query(models.ReplicationRule.state, func.count(models.ReplicationRule.state))
                  .group_by(models.ReplicationRule.state)
                  .with_hint(models.ReplicationRule, 'INDEX_FFS(rules RULES_PK)', 'oracle')
                  .all())

        print(result)
        for state, num in result:

    # Count Rules in x state
            gauge_state = state_map.get(repr(state), 'rules_' + repr(state).lower())
            gauge_state = gauge_state.replace("<", "").replace(">", "").split(':')[0]
            print('rules.count.%s %s' % (gauge_state, num))

            prom_labels = {'state': gauge_state}
            prom_labels.update(extra_prom_labels)
            rules_count_gauge.labels(**prom_labels).set(num)

            monitor.record_gauge(name='rules.count.%s' % (gauge_state), value=num)

    # Not Ok rules
        query = session.query(models.ReplicationRule.scope).filter(models.ReplicationRule.state != RuleState.OK)
        result = get_count(query)

        prom_labels = {'Not_ok_rules': 'Not_ok_rules'}
        prom_labels.update(extra_prom_labels)
        not_ok_rules_gauge.labels(**prom_labels).set(result)

        monitor.record_gauge(name='judge.total_not_OK_rules', value=result)

    # Stuck cnt
        query = (session.query(func.sum(models.ReplicationRule.locks_stuck_cnt))
                 .filter(models.ReplicationRule.state == RuleState.STUCK))
        result = query.scalar() or 0

        print('rules.no_of_files.total.sum_locks_stuck_cnt %s' % (result))

        prom_labels = {'Stuck_cnt': 'Stuck_cnt'}
        prom_labels.update(extra_prom_labels)
        stuck_cnt_gauge.labels(**prom_labels).set(result)

        monitor.record_gauge(name='rules.no_of_files.total.sum_locks_stuck_cnt', value=result)

    # check left replicating files
        query = (session.query(func.sum(models.ReplicationRule.locks_replicating_cnt))
                 .filter(models.ReplicationRule.state.in_([RuleState.STUCK, RuleState.REPLICATING])))
        result = query.scalar() or 0

        print('rules.no_of_files.total.sum_locks_replicating_cnt %s' % (result))

        prom_labels = {'Replicating_cnt': 'Replicating_cnt'}
        prom_labels.update(extra_prom_labels)
        replicating_cnt_gauge.labels(**prom_labels).set(result)

        monitor.record_gauge(name='rules.no_of_files.total.sum_locks_replicating_cnt', value=result)

    # check stuck and replicating files which are more than X old
        for a_name, a_delta in ages.items():
            timeLimit = datetime.datetime.utcnow() - a_delta

            stuck_locks_older_than_X_labels = ['Stuck_cnt']
            replicating_locks_older_than_X_labels = ['Replicating_cnt']

            stuck_locks_older_than_X_labels.extend(extra_prom_labels.keys())
            replicating_locks_older_than_X_labels.extend(extra_prom_labels.keys())

            stuck_locks_older_than_gauge = Gauge('rucio_stuck_cnt_%s' % a_name, 'Number of stuck files older than X',
                                                 labelnames=stuck_locks_older_than_X_labels,
                                                 registry=registry)
            replicating_locks_older_than_gauge = Gauge('rucio_replicating_cnt_%s' % a_name,
                                                       'Number of replicating files older than X',
                                                       labelnames=replicating_locks_older_than_X_labels,
                                                       registry=registry)

            query = (session.query(func.sum(models.ReplicationRule.locks_stuck_cnt))
                     .filter(models.ReplicationRule.state == RuleState.STUCK)
                     .filter(models.ReplicationRule.created_at <= timeLimit))
            result = query.scalar() or 0
            print('rules.no_of_files.stuck.%s.sum_locks_stuck_cnt %s' % (a_name, result))

            prom_labels = {'Stuck_cnt': 'Stuck_files.%s.Sum' % a_name}
            prom_labels.update(extra_prom_labels)
            stuck_locks_older_than_gauge.labels(**prom_labels).set(result)

            monitor.record_gauge(name='rules.no_of_files.stuck.%s.sum_locks_stuck_cnt' % a_name, value=result)

            query = (session.query(func.sum(models.ReplicationRule.locks_replicating_cnt))
                     .filter(models.ReplicationRule.state.in_([RuleState.STUCK, RuleState.REPLICATING]))
                     .filter(models.ReplicationRule.created_at <= timeLimit))
            result = query.scalar() or 0
            print('rules.no_of_files.replicating.%s.sum_locks_replicating_cnt %s' % (a_name, result))

            prom_labels = {'Replicating_cnt': 'Replicating_files.%s.Sum' % a_name}
            prom_labels.update(extra_prom_labels)
            replicating_locks_older_than_gauge.labels(**prom_labels).set(result)

            monitor.record_gauge(name='rules.no_of_files.replicating.%s.sum_locks_replicating_cnt' % a_name,
                                 value=result)
        if PROM_SERVERS:
            for server in PROM_SERVERS:
                try:
                    push_to_gateway(server.strip(), job='check_rules_count_by_state_by_account', registry=registry)
                except:
                    continue
    except:
        print(traceback.format_exc())
        sys.exit(UNKNOWN)
    finally:
        session.remove()
    sys.exit(OK)

