#!/usr/bin/env python3
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Eric Vaandering, <ewv@fnal.gov>, 2021

"""
Probe to check the backlog of stuck rules which have not moved per rse.
"""

import sys
import traceback

from rucio.core import monitor
from rucio.db.sqla.session import BASE, get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if BASE.metadata.schema:
    schema = BASE.metadata.schema + '.'
else:
    schema = ''

if __name__ == "__main__":
    try:
        session = get_session()
        sql = 'SELECT rse_expression,sum(bytes*copies) as sum_bytes FROM {schema}DIDS join {schema}RULES on DIDS.name = RULES.name where (state!=\'O\' and locks_ok_cnt=0) group by rse_expression'.format(
            schema=schema)
        result = session.execute(sql).fetchall()
        for rse, bytes in result:
            if not bytes:
                bytes = 0
            monitor.record_gauge('judge.rules_with_0_completion_volume.%s' % rse, value=bytes)
    except:
        print(traceback.format_exc())
        sys.exit(UNKNOWN)
    sys.exit(OK)

