#!/usr/bin/env python3
# Copyright 2012-2020 CERN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Vincent Garonne, <vincent.garonne@cern.ch>, 2013
# - Thomas Beermann, <thomas.beermann@cern.ch>, 2019
# - Fernando Garzon, <oscar.fernando.garzon.miguez@cern.ch>, 2020
# - Donata Mielaikaite, <donata.mielaikaite@cern.ch>, 2020
# - Eric Vaandering, <ewv@fnal.gov>, 2021


"""
Probe to check the backlog of unlocked replicas per RSE.
"""

import sys
from datetime import (datetime, timedelta)

from rucio.db.sqla import models
from rucio.db.sqla.session import get_session
from sqlalchemy import func

from utils import common

probe_metrics = common.probe_metrics

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

t1 = timedelta(hours=2, minutes=0)

if __name__ == '__main__':
    try:
        session = get_session()
        query = (session.query(models.RSE.rse, func.count(models.RSEFileAssociation.name))
                 .with_hint(models.RSEFileAssociation, 'index_fss(%(name)s REPLICAS_TOMBSTONE_IDX)')
                 .join(models.RSE, (models.RSEFileAssociation.rse_id == models.RSE.id))
                 .filter(models.RSEFileAssociation.tombstone != None).group_by(models.RSE.rse))
        result = query.all()
        print('Number of unlocked replicas per RSE')
        for rse, num in result:
            probe_metrics.gauge('reaper.unlocked_rse_replicas.{rse}').labels(rse=rse).set(num)
            print(rse, num)
        query = (session.query(models.RSE.rse, func.count(models.RSEFileAssociation.name))
                 .with_hint(models.RSEFileAssociation, 'index_fss(%(name)s REPLICAS_TOMBSTONE_IDX)')
                 .join(models.RSE, (models.RSEFileAssociation.rse_id == models.RSE.id))
                 .filter(models.RSEFileAssociation.tombstone != None)
                 .filter(models.RSEFileAssociation.tombstone < datetime.utcnow() - t1)
                 .group_by(models.RSE.rse))
        print('Number of expired replicas per RSE')
        for rse, num in result:
            probe_metrics.gauge('reaper.expired_rse_replicas.{rse}').labels(rse=rse).set(num)
            print(rse, num)
    except Exception as error:
        print(error)
        status = UNKNOWN
        sys.exit(status)
    sys.exit(OK)
