#!/usr/bin/env python
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Vincent Garonne, <vincent.garonne@cern.ch>, 2013
# - Thomas Beermann, <thomas.beermann@cern.ch>, 2019

'''
Probe to check the backlog of expired dids.
'''
import sys
import traceback

from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

from rucio.common.config import config_get
from rucio.core import monitor
from rucio.db.sqla.session import BASE, get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if BASE.metadata.schema:
    schema = BASE.metadata.schema + '.'
else:
    schema = ''

PROM_SERVERS = config_get('monitor', 'prometheus_servers', raise_exception=False, default='')
if PROM_SERVERS != '':
    PROM_SERVERS = PROM_SERVERS.split(',')

if __name__ == "__main__":
    try:
        registry = CollectorRegistry()
        session = get_session()
        expired_dids = 'select count(*) from {schema}dids where expired_at is not null and expired_at < sys_extract_utc(localtimestamp)'.format(schema=schema)
        result = session.execute(expired_dids).fetchone()[0]
        # Possible check against a threshold. If result > max_value then sys.exit(CRITICAL)

        monitor.record_gauge(stat='undertaker.expired_dids', value=result)
        Gauge('undertaker_expired_dids', '', registry=registry).set(result)

        if len(PROM_SERVERS):
            for server in PROM_SERVERS:
                try:
                    push_to_gateway(server.strip(), job='check_expired_dids', registry=registry)
                except:
                    continue

        print result
    except:
        print traceback.format_exc()
        sys.exit(UNKNOWN)
    sys.exit(OK)
