#!/usr/bin/env python
"""
 Copyright European Organization for Nuclear Research (CERN)

 Licensed under the Apache License, Version 2.0 (the "License");
 You may not use this file except in compliance with the License.
 You may obtain a copy of the License at
                       http://www.apache.org/licenses/LICENSE-2.0

 Authors:
 - Jaroslav Guenther, <jaroslav.guenther@cern.ch>, 2019

 Testing Authorisation flows against Identity Provider (IdP) (XDC IAM at the moment):

 1. Authorisation Code Flow - can be used for interactions between Rucio Web UI and Rucio infrastructure

 2. Implicit Code Flow - without the 'authz code bit, useful if no User-Agent stands between the user and the user and the '

In both cases above the Rucio Client has to authenticate on
an IAM login page with a username and password before proceeding
(post request within the authorise_idp_client flow )
This can be avoided in case IAM marks Rucio Client as trusted.

"""
