#!/usr/bin/env python3
# Copyright European Organization for Nuclear Research (CERN) since 2012
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Probe to check the queues of the transfer service
"""
import sys
import traceback
from urllib.parse import urlparse

from sqlalchemy import func, select

from rucio.db.sqla import models
from rucio.db.sqla.session import get_session

from utils.common import PrometheusPusher

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == "__main__":
    try:
        session = get_session()
        statement = select(
            models.Request.state,
            models.Request.activity,
            models.Request.external_host,
            func.count()
        ).group_by(
            models.Request.state,
            models.Request.activity,
            models.Request.external_host
        )

        with PrometheusPusher() as manager:
            for row in session.execute(statement):
                state = f"queues.requests.{row.state.name.lower()}"
                activity = row.activity.replace(" ", "_")
                if row.external_host is not None:
                    external_host = urlparse(row.external_host).hostname.replace(".", "_")
                else:
                    external_host = 'no_fts_host'

                print(f"{state}.{activity}.{external_host} {row.count}")
                (manager.gauge(
                        "transfer.{state}.{activity}.{external_host}",
                        documentation="Status of requests by state, activity, external host.")
                    .labels(activity=activity, state=state, external_host=external_host)
                    .set(row.count))
    except Exception:
        print(traceback.format_exc())
        sys.exit(UNKNOWN)
    sys.exit(OK)
