#!/usr/bin/env python
# Copyright European Organization for Nuclear Research (CERN) 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Fernando Garzon. oscar.fernando.garzon.miguez@cern.ch 

"""
Probe to check the nember of not OK rules.
"""

import sys
import traceback

from rucio.core import monitor
from rucio.db.sqla.session import BASE, get_session

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if BASE.metadata.schema:
    schema = BASE.metadata.schema + '.'
else:
    schema = ''

if __name__ == "__main__":
    try:
        session = get_session()
        sql = 'SELECT count(*) from {schema}RULES where state=\'O\''.format(schema=schema)
        result = session.execute(sql).fetchall()
        monitor.record_gauge(stat='judge.total_OK_rules', value=result[0][0])
    except:
        print traceback.format_exc()
        sys.exit(UNKNOWN)
    sys.exit(OK)
