#!/usr/bin/env python3
# Copyright European Organization for Nuclear Research (CERN) since 2012
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Calculate the amount of obsolete replicas and update the RSE usage counters.
"""

import sys
import traceback

from sqlalchemy import func, select

from rucio.db.sqla import models
from rucio.db.sqla.constants import OBSOLETE
from rucio.db.sqla.session import get_session
from rucio.gateway.rse import list_rses, set_rse_usage

OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3

if __name__ == '__main__':
    try:
        session = get_session()
        for rse in list_rses(session=session):
            query = select(
                func.coalesce(func.sum(models.RSEFileAssociation.bytes), 0).label('bytes'),
                func.count().label('files')
            ).with_hint(
                models.RSEFileAssociation, 'INDEX(replicas REPLICAS_RSE_ID_TOMBSTONE_IDX)', 'oracle'
            ).where(
                models.RSEFileAssociation.rse_id == rse['id'],
                models.RSEFileAssociation.tombstone == OBSOLETE
            )

            bytes_, files = session.execute(query).one()
            set_rse_usage(rse=rse['rse'], source='obsolete', used=bytes_,
                          free=None, issuer='root', files=files,
                          session=session)
    except Exception:
        print(traceback.format_exc())
        sys.exit(UNKNOWN)
    sys.exit(OK)
