#!/usr/bin/env python
# Copyright European Organization for Nuclear Research (CERN) since 2012
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

'''
Probe to check the min free space.
'''

import sys
import traceback

from rucio.core.rse import list_rses, get_rse_limits, set_rse_usage

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3


if __name__ == "__main__":
    try:

        for rse in list_rses():
            limits = get_rse_limits(rse=rse['rse'], rse_id=rse['id'])
            min_free_space = limits.get('MinFreeSpace')
            if min_free_space is not None:
                # print rse['rse'], min_free_space
                set_rse_usage(rse=rse['rse'], source='min_free_space', used=min_free_space, free=None)
    except:
        print (traceback.format_exc())
        sys.exit(UNKNOWN)
    sys.exit(OK)
