#!/usr/bin/env python3
# Copyright European Organization for Nuclear Research (CERN) since 2012
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Probe to check the queues of the transfer service
"""
import sys
from urllib.parse import urlparse

from rucio.db.sqla import models
from rucio.db.sqla.session import get_session
from sqlalchemy import func, select

from utils.common import PrometheusPusher

# Exit statuses
OK, WARNING, CRITICAL, UNKNOWN = 0, 1, 2, 3


if __name__ == "__main__":
    try:
        session = get_session()
        active_queue = select(
            models.Request.state,
            models.Request.activity,
            models.Request.external_host,
            func.count()
        ).group_by(
            models.Request.state,
            models.Request.activity,
            models.Request.external_host
        )
        with PrometheusPusher() as manager: 
            for k in session.execute(active_queue).fetchall():
                state = k.state.name.lower()
                activity = k.activity.replace(" ", "-")
                if k.external_host is not None:
                    external_host = urlparse(k.external_host).hostname.replace(".", "_")
                else: 
                    external_host = 'no_fts_host'
                print(f"{state}.{activity}.{external_host}", k.count)

            manager.gauge(
                name = 'conveyor_queues_requests.{activity}.{state}.{external_host}', 
                documentation='Queued request for conveyor daemons by activity, state, and host.'
            ).labels(
                activity=activity, 
                state=state, 
                external_host=external_host
            ).set(k.count)

    except:
        sys.exit(UNKNOWN)
    sys.exit(OK)
